#!/bin/bash
TESTING=True \
TEST_DATABASE_URL=sqlite:///./test.db \
USER_INFO_SERVICE_ENDPOINT=http://user-info-service:80 \
pipenv run pytest --cov-report=xml --cov=app && \
pipenv run codecov --commit=$1 -t $2
